// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddTodoRequest struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type MarkAsDoneRequest struct {
	ID string `json:"id"`
}

type RemoveTodoRequest struct {
	ID string `json:"id"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type UpdateTodoRequest struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
